# Generated by Django 5.1.3 on 2024-12-24 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masseges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massegeText', models.TextField()),
                ('senderName', models.CharField(max_length=50)),
                ('senderNumber', models.CharField(max_length=50)),
                ('reciver', models.CharField(max_length=50)),
                ('received', models.BooleanField(default=False)),
                ('creat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
